#!/bin/zsh
# xkill for niri, but the way people think xkill actually works
# click a window, pid attached to that window is killed
if [[ "$XDG_CURRENT_DESKTOP" != "niri" ]] then
	echo "nkill only works on niri"
	return 1
fi
kill $(niri msg -j pick-window | jq '.pid')
